project:
  root_path: "D:\\GitDev\\DB"
  branch_name: "development"

base_release:
  base_version: "DFNNTP-DB_SA_MSSA_10.040.1.1"

hotfix_release:
  hotfix_type: "QA" #QA,UAT

scripts_source:
  source_folder: "source"